### PR TITLE
fix integration test error

### PR DESCRIPTION
**Pull request by ycyaoxdu**
fix: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/66

### CODE REVIEW

**Comment by ycyaoxdu** [comment]
fix https://github.com/open-cluster-management-io/multicluster-controlplane/issues/66

**Comment by clyang82** [comment]
Do you know why the integration is failed, but the test is marked as Passed?

**Comment by ycyaoxdu** [comment]
> Do you know why the integration is failed, but the test is marked as Passed?

@clyang82 We didn't check the result of the command execution.

**Comment by clyang82** [comment]
maybe we add it to ensure we catch the result and popup the result accordingly.

**Pull request merged**
