### PR TITLE
performance test

### PR DESCRIPTION
**Pull request by skeeey**

### CODE REVIEW

**Review by clyang82 — COMMENTED** [review]
Could you please add a document to describe the performance test under `test/performance` folder? And how to run the performance test. capacity requirements?

**Comment by skeeey** [comment]
> Could you please add a document to describe the performance test under `test/performance` folder? And how to run the performance test. capacity requirements?

yeah, I will use a new pr to add a document showing how to run the performance test

**Review by clyang82 — APPROVED** [review]

**Pull request merged**
