### PR TITLE
upgrade github action

### PR DESCRIPTION
**Pull request by ycyaoxdu**
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
@ycyaoxdu Can you rebase or merge this PR onto the main branch?  This e2e error has been fixed in the main branch. https://github.com/open-cluster-management-io/multicluster-controlplane/pull/21

**Comment by ycyaoxdu** [comment]
> 

sure

**Pull request merged**
